### PR TITLE
Pins `ncurses` to 5.9

### PR DESCRIPTION
**Pull request by jakirkham**
Pins `ncurses` to 5.9 to match our [pinning wiki](https://github.com/conda-forge/staged-recipes/wiki/Pinned-dependencies).

### CODE REVIEW

**Comment by croth1** [comment]
What happens if we want to upgrade the pinned version? Do all recipes have to be edited manually?

**Comment by jakirkham** [comment]
> What happens if we want to upgrade the pinned version? Do all recipes have to be edited manually?

We have played with a script for generating bulk pinning PRs. This is not automated yet.

Also, I should note that many people have added PRs for pinning proposals to `conda-build`. It is not clear to me that any of them are getting enough traction to get accepted at this point. Even if one of them is accepted, it remains unclear how useful they would be for a large scale endeavor like conda-forge.

For instance, we benefit by having certain base dependencies in our stack pinned with the same version. In that case, it doesn't matter what latest is. Instead it matters that we have rebuilt everything that needs to be pinned with the new pinnings, bumped build numbers, and had packages deployed in the right order. The kind of automation that would be needed here may or may not overlap with what is decided for `conda-build` at all depending on the proposal.

This all being said, I don't know that is worth fretting over doing this manually. This is the advantage of the nice community we have here. This doesn't all fall on one person's shoulders and we can work together to change things as needed. We went through one iteration of this previously. Though it was a bit rocky given it was our first, everything worked out fine in the end.

**Comment by jakirkham** [comment]
Going to bring this one home as it is a simple change and it's my bad we didn't do this in staged-recipes.

**Comment by pelson** [comment]
May need to remove the old build. It may get picked up when we release a new ncurses and fail 😢

**Comment by jakirkham** [comment]
> May need to remove the old build. It may get picked up when we release a new ncurses and fail 😢

Yeah, we might. As we will want to package `ncurses` 6.0 at some point given it is already out. Sorry about that. Should have caught this in the review at staged-recipes.

As we do automate this stuff more, it may be worth having the linter or something similar review pinned dependencies to make sure they are in good order. We may need to break with it occasionally, but at least we will have been reminded that we are going astray.

**Comment by pelson** [comment]
> As we do automate this stuff more, it may be worth having the linter or something similar review pinned dependencies to make sure they are in good order. We may need to break with it occasionally, but at least we will have been reminded that we are going astray.

Yes, that is reasonable, though we do have the tooling to inspect this manually:

```
$ conda execute conda-forge.github.io/scripts/list_deps.py conda-forge --dependencies "ncurses$"
Fetching package metadata: ..
erlang 18.3 0 None                 : ncurses
erlang 18.3 1 None                 : ncurses
lua 5.1.5 0 None                   : ncurses
readline 6.3 0 None                : ncurses
```

**Pull request merged**
