### PR TITLE
Readline 7.0

### PR DESCRIPTION
**Pull request by asmeurer**
Hope it works :)

### CODE REVIEW

**Comment by asmeurer** [comment]
Looks like the Miniconda install failed on Travis.

**Comment by asmeurer** [comment]
@conda-forge/core

**Comment by ocefpaf** [comment]
Can you rerender? That will probably fix w
the miniconda download.

**Comment by asmeurer** [comment]
Done.

**Comment by asmeurer** [comment]
It [didn't upload](https://travis-ci.org/conda-forge/readline-feedstock#L1031): "No BINSTAR_TOKEN present, so no upload is taking place. The distribution just built is not already available on conda-forge's main channel."

**Comment by ocefpaf** [comment]
That is the CI on the PR. The CI on master, which does the upload, did not finish yet.

See https://travis-ci.org/conda-forge/readline-feedstock/builds/199982038

**Comment by asmeurer** [comment]
Ah, Travis UI fooled me again.

**Comment by asmeurer** [comment]
It's basically impossible to install because Python pins readline. Can we look at updating the pinning? I don't know if it will break anything.

**Comment by ocefpaf** [comment]
You can suggest that with a PR to https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py#L64

**Comment by asmeurer** [comment]
Would have never guessed to look in the website repo for build scripts.

**Pull request merged**
