### PR TITLE
 MNT: Re-rendered with conda-smithy 3.1.6 and pinning 2018.07.20 

### PR DESCRIPTION
**Pull request by bgruening**
+ compiler changes and pin against new ncurses library.

### CODE REVIEW

**Comment by asmeurer** [comment]
Are the pins actually updated? I think you might need to run

```
conda smithy update-cb3
conda smithy rerender
```

**Comment by bgruening** [comment]
`update-cb3` is resulting in `requests.exceptions.InvalidSchema: No connection adapters were found for 'ftp://ftp.gnu.org/gnu/readline/readline-7.0.tar.gz'` for me. But a new rerendering has helped. I guess I needed to at first fix the recipe manually and then rerender.

Thanks for the catch.

**Review by isuruf — APPROVED** [review]

**Comment by asmeurer** [comment]
I think there's a way to make requests work with ftp. I would open a bug in the smithy repo with a full traceback.

**Comment by asmeurer** [comment]
Anyway we can worry about that later, unless there's a non ftp URL we can put in the recipe for the command.

**Comment by bgruening** [comment]
@asmeurer I filled a bug. Can we merge this PR?

**Pull request merged**
