### PR TITLE
Add @jakirkham and friends

### PR DESCRIPTION
**Pull request by jakirkham**
Add myself as a maintainer.

### CODE REVIEW

**Comment by jakirkham** [comment]
@jjhelmus @msarahan @pelson @ocefpaf, do you guys want to be added as maintainers? I would be happy to add you in this PR.

**Comment by pelson** [comment]
> do you guys want to be added as maintainers? 

👍  from me 

You might also consider `[skip ci]` on this PR to reduce the CI overhead.

**Comment by jjhelmus** [comment]
Sounds good to me.

**Comment by msarahan** [comment]
OK with me

**Comment by jakirkham** [comment]
Thanks everyone will add all of you here.

> You might also consider `[skip ci]` on this PR to reduce the CI overhead.

Yeah, I added this in GitHub web interface and forgot to add it in the commit. They don't let you do any of the fun stuff (`commit --amend`, `rebase`, etc.) 😈.

**Pull request merged**
