### PR TITLE
Add readline 6.2.x

### PR DESCRIPTION
**Pull request by jakirkham**
This adds a `readline` 6.2.x build here in the `v6_2_x` branch. Patches are updated based on the ones in this [ftp directory](http://ftp.gnu.org/gnu/readline/readline-6.2-patches/).

All files were downloaded and had there GPG signatures verified. This includes the tarball before computing the checksum.

This built locally on my Mac, but I didn't test Linux. Hoping it will just work. Let's see what the CIs say though.

### CODE REVIEW

**Comment by croth1** [comment]
Is it possible to keep the 6.3.x recipe in a subfolder, like bioconda does? It seems weird that we have to replace the recipe + patches.

**Comment by jakirkham** [comment]
> Is it possible to keep the 6.3.x recipe in a subfolder, like bioconda does?

The feedstock is designed to house only one recipe. So we place different versions in different branches instead. It really is no more or less cumbersome than handling multiple versions in different branches for large scale software development efforts.

> It seems weird that we have to replace the recipe + patches.

I don't think I understand your concern here. We are not changing `master`. Instead we are adding this to a new branch `v6_2_x`, which holds the recipe to build the `6.2` version. In `master`, we will still build `6.3`. In fact, we will continue to build both releases. Not sure if this is what you are concerned about or not. Maybe a bit clearer explanation would help me understand better.

**Comment by croth1** [comment]
Oh, the branching concept makes sense. I didn't see that this will not simply replace the master. Totally makes sense!

**Comment by jakirkham** [comment]
Awesome. Glad that clarified it for you.

**Comment by pelson** [comment]
@jakirkham - out of interest, what is the motivation for readline 6.2 vs 6.3?

**Comment by jakirkham** [comment]
As we are pinned to 6.2 currently. I thought maybe we should take over the reigns. 🏇

**Comment by jakirkham** [comment]
Thanks @pelson.

**Comment by croth1** [comment]
hmh, should we make a 6_3_x branch as well? Otherwise we don't have the original recipe anymore, do we?

**Comment by jakirkham** [comment]
> hmh, should we make a 6_3_x branch as well? Otherwise we don't have the original recipe anymore, do we?

No need. `master` is kept as the latest version. We should only add such a branch if we want to maintain 6.3, but we start building 6.4 also.

**Pull request merged**
